#if os(Linux)
extension WrapTests {
    static var allTests = [
        ("testBasicStruct", testBasicStruct),
        ("testOptionalProperties", testOptionalProperties),
        ("testProtocolProperties", testProtocolProperties),
        ("testRootEnum", testRootEnum),
        ("testEnumProperties", testEnumProperties),
        ("testDateProperty", testDateProperty),
        ("testDatePropertyWithCustomizableStruct", testDatePropertyWithCustomizableStruct),
        ("testEmptyStruct", testEmptyStruct),
        ("testNestedEmptyStruct", testNestedEmptyStruct),
        ("testArrayProperties", testArrayProperties),
        ("testDictionaryProperties", testDictionaryProperties),
        ("testHomogeneousSetProperty", testHomogeneousSetProperty),
        ("testNSURLProperty", testNSURLProperty),
        ("testURLProperty", testURLProperty),
        ("test64BitIntegerProperties", test64BitIntegerProperties),
        ("testRootSubclass", testRootSubclass),
        ("testRootNSObjectSubclass", testRootNSObjectSubclass),
        ("testRootDictionary", testRootDictionary),
        ("testNestedStruct", testNestedStruct),
        ("testNestedArrayOfStructs", testNestedArrayOfStructs),
        ("testNestedDictionariesOfStructs", testNestedDictionariesOfStructs),
        ("testNestedSubclass", testNestedSubclass),
        ("testDeepNesting", testDeepNesting),
        ("testObjectiveCObjectProperties", testObjectiveCObjectProperties),
        ("testWrappableKey", testWrappableKey),
        ("testKeyCustomization", testKeyCustomization),
        ("testCustomWrapping", testCustomWrapping),
        ("testCustomWrappingCallingWrapFunction", testCustomWrappingCallingWrapFunction),
        ("testCustomWrappingForSingleProperty", testCustomWrappingForSingleProperty),
        ("testCustomWrappingFailureThrows", testCustomWrappingFailureThrows),
        ("testCustomWrappingForSinglePropertyFailureThrows", testCustomWrappingForSinglePropertyFailureThrows),
        ("testInvalidRootObjectThrows", testInvalidRootObjectThrows),
        ("testDataWrapping", testDataWrapping),
        ("testWrappingArray", testWrappingArray),
        ("testSnakeCasedKeyWrapping", testSnakeCasedKeyWrapping),
        ("testContext", testContext),
        ("testInheritance", testInheritance),
        ("testIgnoringClosureProperties", testIgnoringClosureProperties)
    ]
}
#endif
